name: Hello Workflow

on: 
  push:
    branches:
      - develop   # 👈 run only when code is pushed to develop branch

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "👋 Hello from GitHub Actions on develop branch!"
